/* chunk.txt の英語・日本語を変更せずに収録。見出しの番号のみ除いています。 */
const CHUNKS = Object.freeze([
  {"id":1,"category":"話を始める・自分の大学について述べる","en":"At our university,","ja":"本学では","example":"At our university, we support researchers through our institutional repository."},
  {"id":2,"category":"話を始める・自分の大学について述べる","en":"In our case,","ja":"私たちの場合は","example":"In our case, the library handles most of the deposit process."},
  {"id":3,"category":"話を始める・自分の大学について述べる","en":"In Japan,","ja":"日本では","example":"In Japan, many universities operate institutional repositories."},
  {"id":4,"category":"話を始める・自分の大学について述べる","en":"In our repository,","ja":"本学のリポジトリでは","example":"In our repository, we mainly provide access to research outputs."},
  {"id":5,"category":"話を始める・自分の大学について述べる","en":"From our perspective,","ja":"私たちの立場では","example":"From our perspective, reducing researchers' workload is important."},
  {"id":6,"category":"話を始める・自分の大学について述べる","en":"In terms of open access,","ja":"OAの観点では","example":"In terms of open access, green OA is especially important for us."},
  {"id":7,"category":"話を始める・自分の大学について述べる","en":"When it comes to OA,","ja":"OAについて言えば","example":"When it comes to OA, awareness is still a challenge."},
  {"id":8,"category":"話を始める・自分の大学について述べる","en":"As for our workflow,","ja":"ワークフローについては","example":"As for our workflow, researchers first submit a request."},
  {"id":9,"category":"話を始める・自分の大学について述べる","en":"At the moment,","ja":"現時点では","example":"At the moment, we are still developing the service."},
  {"id":10,"category":"話を始める・自分の大学について述べる","en":"So far,","ja":"これまでのところ","example":"So far, we have received only a few applications."},
  {"id":11,"category":"説明をつなぐ","en":"Basically,","ja":"基本的には","example":"Basically, the library checks the publisher's policy."},
  {"id":12,"category":"説明をつなぐ","en":"In general,","ja":"一般的には","example":"In general, researchers submit a request through an online form."},
  {"id":13,"category":"説明をつなぐ","en":"For example,","ja":"例えば","example":"For example, we may ask for the accepted manuscript."},
  {"id":14,"category":"説明をつなぐ","en":"For instance,","ja":"例えば","example":"For instance, some publishers require an embargo."},
  {"id":15,"category":"説明をつなぐ","en":"In other words,","ja":"言い換えると","example":"In other words, the library handles the deposit on behalf of researchers."},
  {"id":16,"category":"説明をつなぐ","en":"In that case,","ja":"その場合","example":"In that case, we set an embargo period."},
  {"id":17,"category":"説明をつなぐ","en":"If necessary,","ja":"必要であれば","example":"If necessary, we contact the researcher again."},
  {"id":18,"category":"説明をつなぐ","en":"If possible,","ja":"可能であれば","example":"If possible, we make the article available immediately."},
  {"id":19,"category":"説明をつなぐ","en":"Depending on the situation,","ja":"状況によって","example":"Depending on the situation, we may need additional information."},
  {"id":20,"category":"説明をつなぐ","en":"Depending on the policy,","ja":"方針によって","example":"Depending on the policy, we may need to set an embargo."},
  {"id":21,"category":"手順・ワークフロー","en":"The first step is","ja":"最初のステップは","example":"The first step is to submit a request."},
  {"id":22,"category":"手順・ワークフロー","en":"The next step is","ja":"次のステップは","example":"The next step is to check the publisher's policy."},
  {"id":23,"category":"手順・ワークフロー","en":"After that,","ja":"その後","example":"After that, we register the article in the repository."},
  {"id":24,"category":"手順・ワークフロー","en":"Before publication,","ja":"公開前に","example":"Before publication, we check the metadata."},
  {"id":25,"category":"手順・ワークフロー","en":"After publication,","ja":"公開後に","example":"After publication, the item becomes publicly accessible."},
  {"id":26,"category":"手順・ワークフロー","en":"Once we receive it,","ja":"受け取ったら","example":"Once we receive it, we check the publisher's policy."},
  {"id":27,"category":"手順・ワークフロー","en":"Once it is approved,","ja":"承認されたら","example":"Once it is approved, we prepare it for publication."},
  {"id":28,"category":"手順・ワークフロー","en":"Before we publish it,","ja":"公開する前に","example":"Before we publish it, we check the license."},
  {"id":29,"category":"手順・ワークフロー","en":"As part of the workflow,","ja":"ワークフローの一環として","example":"As part of the workflow, we check which version can be deposited."},
  {"id":30,"category":"手順・ワークフロー","en":"through an online form","ja":"オンラインフォームを通じて","example":"Researchers submit their requests through an online form."},
  {"id":31,"category":"登録・申請","en":"submit a request","ja":"申請する","example":"Researchers submit a request to the library."},
  {"id":32,"category":"登録・申請","en":"submit an article","ja":"論文を提出する","example":"Researchers can submit an article for deposit."},
  {"id":33,"category":"登録・申請","en":"deposit an article","ja":"論文を登録する","example":"We deposit an article in the institutional repository."},
  {"id":34,"category":"登録・申請","en":"deposit research outputs","ja":"研究成果を登録する","example":"Our repository can deposit various research outputs."},
  {"id":35,"category":"登録・申請","en":"deposit research data","ja":"研究データを登録する","example":"Researchers can also deposit research data."},
  {"id":36,"category":"登録・申請","en":"upload a manuscript","ja":"原稿をアップロードする","example":"Researchers upload a manuscript through the form."},
  {"id":37,"category":"登録・申請","en":"provide the manuscript","ja":"原稿を提供する","example":"We ask researchers to provide the manuscript."},
  {"id":38,"category":"登録・申請","en":"receive a request","ja":"申請を受ける","example":"We receive a request from a researcher."},
  {"id":39,"category":"登録・申請","en":"receive an application","ja":"申請を受ける","example":"We receive an application through the online form."},
  {"id":40,"category":"登録・申請","en":"handle the deposit","ja":"登録作業を担当する","example":"The library handles the deposit on behalf of researchers."},
  {"id":41,"category":"出版社ポリシー","en":"check the publisher’s policy","ja":"出版社ポリシーを確認する","example":"We check the publisher’s policy before deposit."},
  {"id":42,"category":"出版社ポリシー","en":"check the OA policy","ja":"OAポリシーを確認する","example":"We check the OA policy for each journal."},
  {"id":43,"category":"出版社ポリシー","en":"check the conditions","ja":"条件を確認する","example":"We check the conditions for self-archiving."},
  {"id":44,"category":"出版社ポリシー","en":"check the license","ja":"ライセンスを確認する","example":"We check the license before publication."},
  {"id":45,"category":"出版社ポリシー","en":"under the publisher’s policy","ja":"出版社の方針のもとで","example":"This version can be deposited under the publisher’s policy."},
  {"id":46,"category":"出版社ポリシー","en":"according to the policy","ja":"ポリシーによれば","example":"According to the policy, an embargo is required."},
  {"id":47,"category":"出版社ポリシー","en":"allowed by the publisher","ja":"出版社に許可された","example":"We use the version allowed by the publisher."},
  {"id":48,"category":"出版社ポリシー","en":"permitted for deposit","ja":"登録が許可された","example":"The accepted manuscript is permitted for deposit."},
  {"id":49,"category":"出版社ポリシー","en":"subject to an embargo","ja":"エンバーゴの対象となる","example":"The manuscript may be subject to an embargo."},
  {"id":50,"category":"出版社ポリシー","en":"meet the requirements","ja":"要件を満たす","example":"We make sure the deposit meets the requirements."},
  {"id":51,"category":"論文のバージョン","en":"the accepted manuscript","ja":"著者最終稿","example":"We usually ask for the accepted manuscript."},
  {"id":52,"category":"論文のバージョン","en":"the published version","ja":"出版版","example":"The published version cannot always be deposited."},
  {"id":53,"category":"論文のバージョン","en":"the version of record","ja":"Version of Record","example":"The version of record is available on the publisher's website."},
  {"id":54,"category":"論文のバージョン","en":"the author’s manuscript","ja":"著者原稿","example":"The author’s manuscript may be eligible for deposit."},
  {"id":55,"category":"論文のバージョン","en":"the final manuscript","ja":"最終原稿","example":"We ask the researcher to send us the final manuscript."},
  {"id":56,"category":"論文のバージョン","en":"the permitted version","ja":"許可された版","example":"We deposit the permitted version."},
  {"id":57,"category":"論文のバージョン","en":"which version to use","ja":"どの版を使うか","example":"We check which version to use."},
  {"id":58,"category":"論文のバージョン","en":"which version is allowed","ja":"どの版が許可されるか","example":"We check which version is allowed."},
  {"id":59,"category":"論文のバージョン","en":"the appropriate version","ja":"適切な版","example":"We ask researchers to provide the appropriate version."},
  {"id":60,"category":"論文のバージョン","en":"the latest version","ja":"最新版","example":"Please send us the latest version of the manuscript."},
  {"id":61,"category":"エンバーゴ・公開","en":"set an embargo","ja":"エンバーゴを設定する","example":"If necessary, we set an embargo."},
  {"id":62,"category":"エンバーゴ・公開","en":"during the embargo period","ja":"エンバーゴ期間中","example":"The file remains closed during the embargo period."},
  {"id":63,"category":"エンバーゴ・公開","en":"after the embargo period","ja":"エンバーゴ期間終了後","example":"The article becomes available after the embargo period."},
  {"id":64,"category":"エンバーゴ・公開","en":"once the embargo expires","ja":"エンバーゴ終了後","example":"Once the embargo expires, the article becomes publicly available."},
  {"id":65,"category":"エンバーゴ・公開","en":"without an embargo","ja":"エンバーゴなしで","example":"Some articles can be deposited without an embargo."},
  {"id":66,"category":"エンバーゴ・公開","en":"make it publicly available","ja":"公開する","example":"We make it publicly available through the repository."},
  {"id":67,"category":"エンバーゴ・公開","en":"make it openly available","ja":"オープンにする","example":"Our goal is to make it openly available."},
  {"id":68,"category":"エンバーゴ・公開","en":"provide open access","ja":"OAを提供する","example":"The repository helps provide open access to research."},
  {"id":69,"category":"エンバーゴ・公開","en":"publish it in the repository","ja":"リポジトリで公開する","example":"After checking the policy, we publish it in the repository."},
  {"id":70,"category":"エンバーゴ・公開","en":"available through the repository","ja":"リポジトリを通じて利用可能な","example":"The article is available through the repository."},
  {"id":71,"category":"OAについて説明する","en":"open access to research","ja":"研究へのオープンアクセス","example":"We want to improve open access to research."},
  {"id":72,"category":"OAについて説明する","en":"open access to articles","ja":"論文へのOA","example":"The repository provides open access to articles."},
  {"id":73,"category":"OAについて説明する","en":"green open access","ja":"グリーンOA","example":"We are particularly interested in green open access."},
  {"id":74,"category":"OAについて説明する","en":"gold open access","ja":"ゴールドOA","example":"Some articles are already available through gold open access."},
  {"id":75,"category":"OAについて説明する","en":"immediate open access","ja":"即時OA","example":"The national policy promotes immediate open access."},
  {"id":76,"category":"OAについて説明する","en":"openly available online","ja":"オンラインでOAになっている","example":"The article is already openly available online."},
  {"id":77,"category":"OAについて説明する","en":"on the publisher’s website","ja":"出版社サイト上で","example":"The final version is available on the publisher’s website."},
  {"id":78,"category":"OAについて説明する","en":"through the institutional repository","ja":"機関リポジトリを通じて","example":"We provide access through the institutional repository."},
  {"id":79,"category":"OAについて説明する","en":"increase research visibility","ja":"研究の可視性を高める","example":"Repositories can increase research visibility."},
  {"id":80,"category":"OAについて説明する","en":"improve access to research","ja":"研究へのアクセスを改善する","example":"Open access can improve access to research."},
  {"id":81,"category":"現状・課題を説明する","en":"We’re still working on","ja":"まだ〜に取り組んでいます","example":"We’re still working on raising awareness among researchers."},
  {"id":82,"category":"現状・課題を説明する","en":"We’re currently developing","ja":"現在〜を整備しています","example":"We’re currently developing our research data support."},
  {"id":83,"category":"現状・課題を説明する","en":"We’re still developing","ja":"まだ整備中です","example":"We’re still developing the workflow."},
  {"id":84,"category":"現状・課題を説明する","en":"We’ve recently started","ja":"最近始めました","example":"We’ve recently started accepting green OA requests."},
  {"id":85,"category":"現状・課題を説明する","en":"We recently introduced","ja":"最近導入しました","example":"We recently introduced a new repository system."},
  {"id":86,"category":"現状・課題を説明する","en":"We haven’t done much yet","ja":"まだあまりできていません","example":"We haven’t done much yet in research data management."},
  {"id":87,"category":"現状・課題を説明する","en":"We have limited experience with","ja":"〜の経験はまだ限られています","example":"We have limited experience with research data deposits."},
  {"id":88,"category":"現状・課題を説明する","en":"One challenge is","ja":"課題の一つは","example":"One challenge is raising awareness among researchers."},
  {"id":89,"category":"現状・課題を説明する","en":"One issue is","ja":"問題の一つは","example":"One issue is the workload for researchers."},
  {"id":90,"category":"現状・課題を説明する","en":"A major challenge is","ja":"大きな課題は","example":"A major challenge is making the process easy to understand."},
  {"id":91,"category":"相手に質問する","en":"How do you handle","ja":"〜にはどう対応していますか","example":"How do you handle embargoes at your university?"},
  {"id":92,"category":"相手に質問する","en":"How does it work","ja":"どのような仕組みですか","example":"How does it work at your institution?"},
  {"id":93,"category":"相手に質問する","en":"What is your approach to","ja":"〜への取り組みはどのようなものですか","example":"What is your approach to green open access?"},
  {"id":94,"category":"相手に質問する","en":"What kind of support","ja":"どのような支援","example":"What kind of support do you provide to researchers?"},
  {"id":95,"category":"相手に質問する","en":"What role does the library play","ja":"図書館はどんな役割を担っていますか","example":"What role does the library play in research data management?"},
  {"id":96,"category":"相手に質問する","en":"Do researchers need to","ja":"研究者は〜する必要がありますか","example":"Do researchers need to deposit their articles themselves?"},
  {"id":97,"category":"相手に質問する","en":"Are researchers required to","ja":"研究者には〜が求められていますか","example":"Are researchers required to provide an accepted manuscript?"},
  {"id":98,"category":"相手に質問する","en":"Who is responsible for","ja":"誰が〜を担当していますか","example":"Who is responsible for checking publisher policies?"},
  {"id":99,"category":"相手に質問する","en":"Could you tell me more about","ja":"〜についてもう少し教えていただけますか","example":"Could you tell me more about your repository workflow?"},
  {"id":100,"category":"相手に質問する","en":"I’d like to learn more about","ja":"〜についてもっと知りたいです","example":"I’d like to learn more about your open access support."}
]);
