/* 教材本文は元の index.html から抽出した正本です。 */
const QUESTIONS = Object.freeze([
  { id: 1, category: "自己紹介・担当", ja: "私は大学図書館で機関リポジトリを担当しています。", en: "I’m in charge of the institutional repository at a university library.", note: "I manage... / I work on... でもOK。", audio: "audio/q001.mp3" },
  { id: 2, category: "自己紹介・担当", ja: "私はオープンアクセスに関する業務も担当しています。", en: "I also work on open access.", note: "短く言える形を優先。", audio: "audio/q002.mp3" },
  { id: 3, category: "自己紹介・担当", ja: "私は研究情報システムにも関わっています。", en: "I’m also involved in our research information system.", note: "be involved in は便利な表現。", audio: "audio/q003.mp3" },
  { id: 4, category: "自己紹介・担当", ja: "私の仕事の一つは、研究成果を公開するための支援です。", en: "One part of my job is supporting the dissemination of research outputs.", note: "supporting researchers in sharing... でもよい。", audio: "audio/q004.mp3" },
  { id: 5, category: "自己紹介・担当", ja: "今日は皆さんの取り組みについて学びたいと思っています。", en: "I’m looking forward to learning about your work today.", note: "訪問冒頭で使いやすい。", audio: "audio/q005.mp3" },
  { id: 6, category: "日本の状況", ja: "日本では多くの大学が機関リポジトリを持っています。", en: "Many universities in Japan have institutional repositories.", note: "In Japan, many universities... でもOK。", audio: "audio/q006.mp3" },
  { id: 7, category: "日本の状況", ja: "機関リポジトリは日本の大学で広く使われています。", en: "Institutional repositories are widely used at Japanese universities.", note: "widely used をひとかたまりで。", audio: "audio/q007.mp3" },
  { id: 8, category: "日本の状況", ja: "大学図書館がリポジトリを運用している場合が多いです。", en: "University libraries often manage institutional repositories.", note: "often manage が使いやすい。", audio: "audio/q008.mp3" },
  { id: 9, category: "日本の状況", ja: "日本ではオープンアクセスへの関心が高まっています。", en: "Interest in open access is growing in Japan.", note: "There is growing interest... でもOK。", audio: "audio/q009.mp3" },
  { id: 10, category: "日本の状況", ja: "最近、日本のオープンアクセス政策には大きな変化がありました。", en: "There have been major changes in open access policy in Japan recently.", note: "Recently, Japan has seen... でもよい。", audio: "audio/q010.mp3" },
  { id: 11, category: "日本の状況", ja: "多くの大学が研究成果の公開方法を見直しています。", en: "Many universities are reviewing how they make research outputs openly available.", note: "reviewing their workflows でもよい。", audio: "audio/q011.mp3" },
  { id: 12, category: "自大学・運用", ja: "私たちの大学では図書館がリポジトリを管理しています。", en: "At our university, the library manages the repository.", note: "At our university を反射的に。", audio: "audio/q012.mp3" },
  { id: 13, category: "自大学・運用", ja: "研究者は論文をリポジトリに登録できます。", en: "Researchers can deposit their papers in the repository.", note: "deposit はこの分野で頻出。", audio: "audio/q013.mp3" },
  { id: 14, category: "自大学・運用", ja: "図書館では登録された内容を確認しています。", en: "The library checks the submitted content.", note: "reviews the submissions でもよい。", audio: "audio/q014.mp3" },
  { id: 15, category: "自大学・運用", ja: "現在、私たちは運用方法を見直しています。", en: "We’re currently reviewing our workflow.", note: "reviewing how we operate it でもOK。", audio: "audio/q015.mp3" },
  { id: 16, category: "自大学・運用", ja: "この仕組みはまだ改善途中です。", en: "This process is still being improved.", note: "We’re still improving this process. でもOK。", audio: "audio/q016.mp3" },
  { id: 17, category: "自大学・運用", ja: "私たちは他の部署とも連携しています。", en: "We also work with other departments.", note: "work with は非常に使いやすい。", audio: "audio/q017.mp3" },
  { id: 18, category: "自大学・運用", ja: "担当は図書館だけではありません。", en: "The library is not the only department involved.", note: "Several departments are involved. でもよい。", audio: "audio/q018.mp3" },
  { id: 19, category: "比較・リアクション", ja: "それは日本でも似た状況です。", en: "That’s similar to the situation in Japan.", note: "That’s similar in Japan. でも通じる。", audio: "audio/q019.mp3" },
  { id: 20, category: "比較・リアクション", ja: "私たちの大学でも似た課題があります。", en: "We have a similar issue at our university.", note: "challenge を使ってもよい。", audio: "audio/q020.mp3" },
  { id: 21, category: "比較・リアクション", ja: "私たちの場合は少し違います。", en: "In our case, it’s a little different.", note: "非常に重要な骨組み。", audio: "audio/q021.mp3" },
  { id: 22, category: "比較・リアクション", ja: "そこは日本とはかなり違います。", en: "That’s quite different from the situation in Japan.", note: "quite different from...", audio: "audio/q022.mp3" },
  { id: 23, category: "比較・リアクション", ja: "それはとても興味深いですね。", en: "That’s very interesting.", note: "まず一言返すための表現。", audio: "audio/q023.mp3" },
  { id: 24, category: "比較・リアクション", ja: "その点は私たちも検討しています。", en: "That’s something we’re also looking into.", note: "looking into は会話向き。", audio: "audio/q024.mp3" },
  { id: 25, category: "比較・リアクション", ja: "私たちも同じような問題を抱えています。", en: "We’re facing a similar problem.", note: "We have the same kind of problem. でもOK。", audio: "audio/q025.mp3" },
  { id: 26, category: "説明を続ける", ja: "基本的には、図書館がこのシステムを管理しています。", en: "Basically, the library manages the system.", note: "Basically, ... を発話の起点に。", audio: "audio/q026.mp3" },
  { id: 27, category: "説明を続ける", ja: "一番大きな課題は、研究者への周知です。", en: "The biggest challenge is raising awareness among researchers.", note: "getting researchers to know about it でもよい。", audio: "audio/q027.mp3" },
  { id: 28, category: "説明を続ける", ja: "もう一つの課題は、業務を効率化することです。", en: "Another challenge is making the workflow more efficient.", note: "streamlining the workflow でもよい。", audio: "audio/q028.mp3" },
  { id: 29, category: "説明を続ける", ja: "研究者によって状況はかなり違います。", en: "The situation varies a lot from researcher to researcher.", note: "It depends on the researcher. でもよい。", audio: "audio/q029.mp3" },
  { id: 30, category: "説明を続ける", ja: "分野によっても違いがあります。", en: "It also varies by discipline.", note: "It depends on the field. でもOK。", audio: "audio/q030.mp3" },
  { id: 31, category: "説明を続ける", ja: "現時点では、まだ明確な答えはありません。", en: "At this point, we don’t have a clear answer yet.", note: "At this point は便利。", audio: "audio/q031.mp3" },
  { id: 32, category: "説明を続ける", ja: "現在、新しい方法を試しているところです。", en: "We’re currently trying a new approach.", note: "trying a new approach を塊で。", audio: "audio/q032.mp3" },
  { id: 33, category: "説明を続ける", ja: "将来的には、もっと自動化したいと考えています。", en: "In the future, we’d like to automate more of the process.", note: "we’d like to... で十分。", audio: "audio/q033.mp3" },
  { id: 34, category: "質問する", ja: "このサービスは誰が管理していますか。", en: "Who manages this service?", note: "短い質問を即座に。", audio: "audio/q034.mp3" },
  { id: 35, category: "質問する", ja: "研究者はどのように論文を登録しますか。", en: "How do researchers deposit their papers?", note: "How do researchers...? の型。", audio: "audio/q035.mp3" },
  { id: 36, category: "質問する", ja: "この仕組みはいつ導入されましたか。", en: "When was this system introduced?", note: "When did you introduce...? でもOK。", audio: "audio/q036.mp3" },
  { id: 37, category: "質問する", ja: "利用状況はどのように把握していますか。", en: "How do you track usage?", note: "How do you measure usage? でもよい。", audio: "audio/q037.mp3" },
  { id: 38, category: "質問する", ja: "研究者にはどのように周知していますか。", en: "How do you promote this to researchers?", note: "How do you communicate this to researchers? でもよい。", audio: "audio/q038.mp3" },
  { id: 39, category: "質問する", ja: "一番大きな課題は何ですか。", en: "What is the biggest challenge?", note: "頻出。", audio: "audio/q039.mp3" },
  { id: 40, category: "質問する", ja: "最近、何か大きな変更はありましたか。", en: "Have there been any major changes recently?", note: "最近の変化を尋ねる。", audio: "audio/q040.mp3" },
  { id: 41, category: "聞き返す・時間を稼ぐ", ja: "すみません、最後の部分が聞き取れませんでした。", en: "Sorry, I didn’t catch the last part.", note: "最重要の立て直し表現。", audio: "audio/q041.mp3" },
  { id: 42, category: "聞き返す・時間を稼ぐ", ja: "もう一度言っていただけますか。", en: "Could you say that again?", note: "短く確実に。", audio: "audio/q042.mp3" },
  { id: 43, category: "聞き返す・時間を稼ぐ", ja: "もう少しゆっくり話していただけますか。", en: "Could you speak a little more slowly?", note: "遠慮なく使ってよい。", audio: "audio/q043.mp3" },
  { id: 44, category: "聞き返す・時間を稼ぐ", ja: "もう少し詳しく説明していただけますか。", en: "Could you explain that in a little more detail?", note: "Could you explain that a little more? でもOK。", audio: "audio/q044.mp3" },
  { id: 45, category: "聞き返す・時間を稼ぐ", ja: "つまり、研究者が自分で登録するということですか。", en: "Do you mean that researchers deposit the content themselves?", note: "Do you mean that...? は重要。", audio: "audio/q045.mp3" },
  { id: 46, category: "聞き返す・時間を稼ぐ", ja: "少し考えさせてください。", en: "Let me think for a moment.", note: "沈黙を怖がらないための一言。", audio: "audio/q046.mp3" },
  { id: 47, category: "聞き返す・時間を稼ぐ", ja: "正確には分かりませんが、たぶんそうだと思います。", en: "I’m not completely sure, but I think so.", note: "断定を避ける。", audio: "audio/q047.mp3" },
  { id: 48, category: "聞き返す・時間を稼ぐ", ja: "それについては詳しくありません。", en: "I’m not very familiar with that.", note: "I don’t know much about that. でもOK。", audio: "audio/q048.mp3" },
  { id: 49, category: "訪問・会話", ja: "今日はお時間をいただき、ありがとうございます。", en: "Thank you for taking the time to meet with us today.", note: "訪問冒頭で便利。", audio: "audio/q049.mp3" },
  { id: 50, category: "訪問・会話", ja: "実際の運用を見せていただけるのは、とても参考になります。", en: "It’s very helpful to see how this works in practice.", note: "in practice が使いやすい。", audio: "audio/q050.mp3" }
]);
